obj-$(CONFIG_MACH_N1) += board-n1.o
obj-$(CONFIG_MACH_N1) += board-n1-camera.o
obj-$(CONFIG_MACH_N1) += board-n1-display.o
obj-$(CONFIG_MACH_N1) += board-n1-gpiomux.o
obj-$(CONFIG_MACH_N1) += board-n1-gpu.o
obj-$(CONFIG_MACH_N1) += board-n1-pmic.o
obj-$(CONFIG_MACH_N1) += board-n1-regulator.o
obj-$(CONFIG_MACH_N1) += board-n1-storage.o
