obj-$(CONFIG_MACH_X909) += board-x909.o
obj-$(CONFIG_MACH_X909) += board-x909-camera.o
obj-$(CONFIG_MACH_X909) += board-x909-display.o
obj-$(CONFIG_MACH_X909) += board-x909-gpiomux.o
obj-$(CONFIG_MACH_X909) += board-x909-gpu.o
obj-$(CONFIG_MACH_X909) += board-x909-pmic.o
obj-$(CONFIG_MACH_X909) += board-x909-regulator.o
obj-$(CONFIG_MACH_X909) += board-x909-storage.o
